"""Use timezone-aware datetime columns

Revision ID: 476c2274870b
Revises: 001
Create Date: 2026-02-14 17:28:02.555655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '476c2274870b'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coffee_options', 'sugar',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('coffee_options', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('coffee_options', 'display_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('coffee_options', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('colleagues', 'usually_in',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('colleagues', 'display_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('colleagues', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('colleagues', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('colleagues', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('drink_types', 'display_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('drink_types', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('magic_link_tokens', 'used',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('magic_link_tokens', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('milk_options', 'display_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('milk_options', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('order_items', 'sugar',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order_items', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('orders', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('sizes', 'display_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sizes', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('users', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('sizes', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('sizes', 'display_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('orders', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('order_items', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('order_items', 'sugar',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('milk_options', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('milk_options', 'display_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('magic_link_tokens', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('magic_link_tokens', 'used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('drink_types', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('drink_types', 'display_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('colleagues', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('colleagues', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('colleagues', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('colleagues', 'display_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('colleagues', 'usually_in',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('coffee_options', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('coffee_options', 'display_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('coffee_options', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('coffee_options', 'sugar',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
